FROM python:3.11-slim

WORKDIR /app

COPY requirements-frontend.txt .

RUN pip install -r requirements-frontend.txt

COPY ui ./ui

EXPOSE 8501

CMD ["streamlit", "run", "ui/app.py", "--server.address=0.0.0.0"]